from typing import Literal

from pydantic import (
    BaseModel,
    Field
)

class ClassificationIn(BaseModel):
    text: str = Field(
        ...,
        min_length=1,
        max_length=5000,
        description="The text to be classified.",
        json_schema_extra={
            "example": "This is a sample text to classify."
        }
    )

class ClassificationOut(BaseModel):
    result: Literal["HUMAN", "AI"] = Field(
        ...,
        description="The classification result indicating whether the text is generated by a human or AI.",
        json_schema_extra={
            "example": "HUMAN"
        }
    )
    probability_ai: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="The probability that the text is generated by AI.",
        json_schema_extra={
            "example": 0.85
        }
    )
    probability_human: float = Field(
        ...,
        ge=0.0,
        le=1.0,
        description="The probability that the text is generated by a human.",
        json_schema_extra={
            "example": 0.15
        }
    )